// <auto-generated />
using System;
using Gear_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gear_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gear_API.Models.Deposito_00", b =>
                {
                    b.Property<int>("Dep_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dep_codigo"), 1L, 1);

                    b.Property<string>("Dep_nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dep_tamanhofazenda")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Dep_tipocadastro")
                        .HasColumnType("int");

                    b.Property<int?>("Dep_tipoplantio")
                        .HasColumnType("int");

                    b.HasKey("Dep_codigo");

                    b.ToTable("Deposito_00");
                });

            modelBuilder.Entity("Gear_API.Models.Estoque_00", b =>
                {
                    b.Property<int>("Etq_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Etq_codigo"), 1L, 1);

                    b.Property<int>("Dep_codigo")
                        .HasColumnType("int");

                    b.Property<string>("Etq_quantidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Etq_validade")
                        .HasColumnType("datetime2");

                    b.HasKey("Etq_codigo");

                    b.ToTable("Estoque_00");
                });

            modelBuilder.Entity("Gear_API.Models.Produto_00", b =>
                {
                    b.Property<int>("Pro_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pro_codigo"), 1L, 1);

                    b.Property<int>("Etq_codigo")
                        .HasColumnType("int");

                    b.Property<string>("Pro_nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Pro_valorcusto")
                        .HasColumnType("float");

                    b.HasKey("Pro_codigo");

                    b.ToTable("Produtos_00");
                });

            modelBuilder.Entity("Gear_API.Models.Users", b =>
                {
                    b.Property<int>("Use_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Use_codigo"), 1L, 1);

                    b.Property<string>("Use_email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Use_nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Usu_senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Use_codigo");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
